// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdykttdsbbcanfjcbsct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkeWt0dGRzYmJjYW5mamNic2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjE1MTUsImV4cCI6MjA1OTY5NzUxNX0.ZhwtKmObar-xzd9rrWE5V44sHS6gwiMJpQZ6JuNpcpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);